### ISSUE TITLE
eval() is security issue

### ISSUE THREAD

**Issue by petrmachcz** [timvink/mkdocs-table-reader-plugin#1]
Using eval() for evaluating untrusted string from markdown text is big security issue.

Use safe literal_eval() for evaluating string literal. 

https://docs.python.org/3/library/ast.html#ast.literal_eval

**Comment by timvink** [comment]
Hi, thanks @petrmachcz for the heads-up.

Works fine locally on mac, but unit tests fail for ubuntu. Will look into it tomorrow.

**Comment by timvink** [comment]
`literal_eval()` has some limitations, like:

```python
# works
eval("pd.util.testing.makeDataFrame().head(3)")
# doesn't work
ast.literal_eval("pd.util.testing.makeDataFrame().head(3)")
```

and

```python
literal_eval("\r\t") #fails
```

I wrote a new module [safe_eval](https://github.com/timvink/mkdocs-table-reader-plugin/blob/master/mkdocs_table_reader_plugin/safe_eval.py) to get around those limitations.

I just released `v.0.2` to include this and some other improvements, see the [release notes](https://github.com/timvink/mkdocs-table-reader-plugin/releases).

Cheers!
