### ISSUE TITLE
Is it possible to add some custom formatting to excel file and render page to html or markdown?

### ISSUE THREAD

**Issue by deepaklearner** [timvink/mkdocs-table-reader-plugin#15]

**Comment by timvink** [comment]
Hi @deepaklearner .

This plugin uses [pd.read_excel](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html) to read excel file as a table. I had a look but I don't see any options to read in formatting as well.

Not sure what you're trying to achieve but you'll need a different route than `mkdocs-table-reader-plugin`
