### ISSUE TITLE
Excel files right aligned by default

### ISSUE THREAD

**Issue by smholvoet** [timvink/mkdocs-table-reader-plugin#24]
Hi 👋

Was just wondering whether there is a way to left align the contents of Excel files (similar to how CSV files get rendered)?

**Excel:**
![image](https://user-images.githubusercontent.com/13507392/150400642-4a2c5f91-add0-4000-94c8-f2bf9d00f46d.png)

**mkdocs:**
![image](https://user-images.githubusercontent.com/13507392/150400698-3a8fde99-76bd-42f1-b7b2-2045d1b3a0d2.png)

Thanks!

**Comment by timvink** [comment]
Hello !

I looked into this, and it wasn't possible but should be. I added the functionality and was inspired to re-write the entire documentation and call it a new major release :)

Checkout the new docs (https://timvink.github.io/mkdocs-table-reader-plugin/)  and let me know if it works for you :)

**Comment by smholvoet** [comment]
Seems like my particular issue was related to me not realizing that [tabulate](https://github.com/astanin/python-tabulate#column-alignment) was responsible for the default column alignment, and changes whether the column contains numbers of just text.

I've made some small changes to the docs (see #25) to clarify this for users who might run into a similar issue in the future.
