### ISSUE TITLE
Allow add list args in fonction

### ISSUE THREAD

**Issue by lynxstarshine** [timvink/mkdocs-table-reader-plugin#33]
This option permit me to use all kwargs in pandas function like the meta args from the function `pandas.json_normalize()` ([source](https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html?highlight=json_normalize))

**Comment by timvink** [comment]
Hi @lynxstarshine ,

I'm not sure I understand. `pd.json_normalize()` is not a function currently supported by thing plugin. 

I sounds like you're looking to do something more advanced. Perhaps [mkdocs-macros-plugin](https://mkdocs-macros-plugin.readthedocs.io/en/latest/) is better suited?

If you want to normalize a json file before reading it to your docs website, you could also consider setting up a [simple hook](https://www.mkdocs.org/user-guide/configuration/#hooks) for that. 

Hope that helps!

**Comment by timvink** [comment]
Closing, feel free to re-open if you can clarify further :)
