### ISSUE TITLE
Support @import statement like Markdown Preview Enhanced

### ISSUE THREAD

**Issue by Rj40x40** [timvink/mkdocs-table-reader-plugin#34]
I use Markdown Preview Enhanced when I use Visual Studio Code to edit Markdown files.
Markdown Preview Enhanced can use the @import statement when importing tables, so I'm using it.
But MkDocs doesn't support @import statements, so it would be great if the table-reader plugin could support them.
I tried cloning it locally to support simple @import and it works fine.

**Comment by timvink** [comment]
Hi @Rj40x40,

So after some searching I support you mean this functionality: https://shd101wyy.github.io/markdown-preview-enhanced/#/file-imports

Mkdocs uses jinja2 templates, which have the `{{` and `}}` syntax. If I add an additional syntax, this might break other use cases. For example, `@import` is also a CSS statement, so it's not unreasonable to expects some users to have those strings in their markdown files.

I see why you find this useful though. We could put this behind an option flag though, like:

```yml
  - table-reader:
      enable_import_statement: false # default
``` 

A follow-up problem might be that you want to specify some of the keyword arguments. 

If we require the `@import` statements to be on their own, unique line, we could also allow follow-up keywords arguments, like so:

```
@import 'tables/basic_table.csv' colalign=("left",)
``` 

And, we'll have to use the extension of the file to find the correct reader (csv, json, tsv, xlsx, etc.). 

I'm open for PRs :)

**Comment by Rj40x40** [comment]
I didn't know the details of MkDocs nor the jinja2 templates.
It's not good to add another syntax when there is a certain one.
Thank you for your explanation.

I agree using option flags to control syntax control.

My prototype code doesn't support optional flags, nor follow-up keywords, but I'll do a PR.

In my prototype code, the relative file paths in @import statements are from the Markdown file location.
Also, like Markdown Preview Enhanced, it only supports double quotes, not single quotes.

The prototype code supports image files as well as csv files.
There seems to be a follow-up keyword defined for image files, but this is not supported.
Since the image file is not a table, I thought that it was out of the scope of this mkdocs-table-reader-plugin, but I just put it in as a trial.

**Comment by timvink** [comment]
This is the place to start: https://www.mkdocs.org/dev-guide/plugins/

**Comment by Rj40x40** [comment]
Thank you for your reply.
As you say, there are some difference so I agree making another plugin for easy choosing.
It's my first challenge, but I'll try to make a plugin.

The CSV converting part is one of difficult parts for me.
I will copy your code with great thanks

**Comment by Rj40x40** [comment]
Thank you for your comment.

My plugin worked fine in my own testing, so I published it.
I will try to register for MkDocs-Plugins soon.
