### ISSUE TITLE
This plugin has been added to the `mkdocs-material` docs

### ISSUE THREAD

**Issue by chrimaho** [timvink/mkdocs-table-reader-plugin#43]
Not really an issue, but I just wanted to let you know that this plugin has been added to the docs page for `mkdocs-material`.

Check it out:
- https://squidfunk.github.io/mkdocs-material/reference/data-tables/#import-table-from-file

**Comment by timvink** [comment]
Cool, thanks for letting me know !

**Comment by timvink** [comment]
Just went through your PR, and the related discussion on reading tables. Thanks for taking the effort to add this the the mkdocs-materials docs! I'm confident you've helped quite some people to be able to find this plugin and start reading in tables from source.
