### ISSUE TITLE
read_csv() bug introduced with 2.2.0: Positional arguments follow keyword arguments

### ISSUE THREAD

**Issue by schneekluth** [timvink/mkdocs-table-reader-plugin#62]
After installing `2.2.0` I am getting an error while using `read_csv()` in MKDocs Material. The issue seems to be related to #61 handling positional arguments as a list. In my case I use `colalign=()`.

The statement I use:
`{{ read_csv('includes/statistics.csv', keep_default_na=False, colalign=('center','center','center','center','center','center','center')) }}` 

The content of `statistics.csv`:
```csv
"Users","Groups","Roles","Categories","Lifecycles","States","Transitions"
"273","91","29","67","28","77","304"
```

Version `2.1.0` shows no errors. But since updating to `2.2.0` I get the following response and MKDocs fails to build:
```zsh
[table-reader-plugin] Make sure the python in your reader tag is correct: Positional arguments follow keyword arguments in ''includes/fnord/vaultdata_statistics.csv', keep_default_na=False, colalign=('center', 
'center', 'center', 'center', 'center', 'center', 'center')'
```

**Comment by timvink** [comment]
Thanks for reporting! Will look into this soon

**Comment by timvink** [comment]
Fixed, making a release now

**Comment by timvink** [comment]
Release https://github.com/timvink/mkdocs-table-reader-plugin/releases/tag/v2.2.1

Pypi https://pypi.org/project/mkdocs-table-reader-plugin/
