### ISSUE TITLE
MKDocs Search only works in Read_CSV

### ISSUE THREAD

**Issue by scottsignal** [timvink/mkdocs-table-reader-plugin#71]
Hello,

I'm not sure if this is a bug or a limitation how MKDOC works.  Was unable to find any more information on it.

I have only tested CSV, JSON, and RAW, however, it seems like CSV is the only format in which the contents are searchable via the MKDOCs Search.  JSON and Raw are absent.  Is this a bug?

Thanks!

**Comment by timvink** [comment]
That sounds strange, as these things are totally unrelated. I would need a bit more info.

Can you give me a small, reproducable example (table, markdown file, mkdocs.yml) and some info on your system (OS, python version (`python -V`), and version of mkdocs and table-reader.

**Comment by scottsignal** [comment]
> That sounds strange, as these things are totally unrelated. I would need a bit more info.
> 
> Can you give me a small, reproducable example (table, markdown file, mkdocs.yml) and some info on your system (OS, python version (`python -V`), and version of mkdocs and table-reader.

Sure, happy to provide.   Possible this is just an order of operations issue/conflict with another plugin we are using.  I can do some more testing with removing other extensions/plugins temporally and report back.

YAML Config (slightly redacted)

`theme:
  name: material
  palette:
    scheme: custom
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.top
    - content.code.copy
    - content.code.annotate
extra_css:
  - assets/extra.css
plugins: 
  - search
  - awesome-pages
  - table-reader
  - markdownextradata
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg`

The box I am running from is running the following (Note this also occurs on Github pages)

Ubuntu 20.04
MKDocs 1.6.0
Python 3.8.10
TableReader 3.0.1

In my MD file:
`{{ read_raw('config.json') }}`

config.json:
`{
  "configuration": [
    {
      "category": "Advanced",
      "component": "NetworkModel",
      "defaultvalue": "false",
      "description": "This will determine if the admin is allowed to deploy.",
      "displaytext": "Admin is allowed to deploy",
      "group": "Miscellaneous",
      "isdynamic": true,
      "name": "deploy.anywhere",
      "subgroup": "Others",
      "type": "Boolean",
      "value": "true"
    }
  ]
}`

Searching anything in the above JSON file doesn't show up in search results.

**Comment by scottsignal** [comment]
Reducing the addons/extentions to just the following results in the same behavior.

~~~
theme:
  name: material
  features:
    - navigation.tabs
plugins: 
  - search
  - table-reader
 ~~~

**Comment by timvink** [comment]
So I created the site, but it's not related to `table-reader`.

I inserted your config.json directly into markdown (without table reader), and the contents won't show up in search

![image](https://github.com/user-attachments/assets/d8fc9cc5-576d-4105-aedb-e185858af9c3)

Indeed if you create a table, it's normal content which is searchable. 

Please open an issue with mkdocs-material instead.

**Comment by scottsignal** [comment]
> So I created the site, but it's not related to `table-reader`.
> 
> I inserted your config.json directly into markdown (without table reader), and the contents won't show up in search
> 
> ![image](https://private-user-images.githubusercontent.com/5570380/361468965-d8fc9cc5-576d-4105-aedb-e185858af9c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODM1NzQsIm5iZiI6MTcyNDY4MzI3NCwicGF0aCI6Ii81NTcwMzgwLzM2MTQ2ODk2NS1kOGZjOWNjNS01NzZkLTQxMDUtYWVkYi1lMTg1ODU4YWY5YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjZUMTQ0MTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhlYzdkOTAxMTU5Y2ExN2U0ZTIzODllNjE1M2YzZjQwMDczM2U4MWNkODM2M2ZlZjgwNDgzY2JiZjQ4ZjZhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rZB0ylF6mA_DkVrftznPWeHxOW5Wa99twWJ-ddq_ZgU)
> 
> Indeed if you create a table, it's normal content which is searchable.
> 
> Please open an issue with mkdocs-material instead.

Ahh, I didn't even think about testing without tablereader.  I will take this over to the MKDocs folks.  Thanks for your help.
